---
- hosts: localhost
  connection: local
  gather_facts: false
  become: yes

  tasks:
    - name: Register the output of uptime command.
      command: uptime
      register: system_uptime

    - name: Print the output of the "uptime" command.
      debug: 
        var: system_uptime['stdout']

    - name: Print a message if uptime resulted in a change.
      debug:
        msg: "Command resulted in a change!"
      when: system_uptime is changed
