---
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    should_fail_via_fail: false
    should_fail_via_assert: false
    should_fail_via_complex_assert: true

  tasks:
    - name: Fail if condition warrant a failure.
      fail:
        msg: "There was an epic failure."
      when: should_fail_via_fail
      ignore_errors: true

    - name: Stop playbook if an assertion is not validated.
      assert:
        that:
          - should_fail_via_assert != true
      ignore_errors: true

    - name: Stop playbook if an complex assertion is not validated.
      assert:
        that:
          - should_fail_via_fail != true
          - should_fail_via_assert != true
          - should_fail_via_complex_assert != true