---
- name: Install Apache.
  hosts: all
  #gather_facts: false
  become: true

  #environment: 
  #  http_proxy: http://example-proxy:80/
  #  https_proxy: https://example-proxy:443/

  vars_files:
    - vars/vars.yml

  pre_tasks:
    - import_tasks: tasks/pre_tasks.yml
  
  handlers:
    - import_tasks: handlers/apache_handlers.yml

  tasks:
    - import_tasks: tasks/apache_tasks.yml
    #- include_tasks: tasks/dynamic_tasks.yml
  
    #- name: Clone website.
    #  git: 

- import_playbook: app.yml