---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/api_key.yml

  environment:
    API_KEY: "{{ myapp_api_key }}"

  tasks:
    - name: Echo the API which is injected into the env.
      shell: echo $API_KEY
      register: echo_result

    - name: Show the results.
      debug: var=echo_result['stdout']