Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"

  # Disable random key created by Vagrant.
  config.ssh.insert_key = false

  # Disable sync folder (/vagrant is folder inside VM)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end

  # App server 1
  config.vm.define "proxy" do |proxy|
    proxy.vm.hostname = "awx-demo-varnish"
    proxy.vm.network :private_network, ip:"192.168.60.30"
  end

  # App server 2
  config.vm.define "app1" do |app|
    app.vm.hostname = "awx-demo-php1"
    app.vm.network :private_network, ip:"192.168.60.31"
  end

  # Database server
  config.vm.define "app2" do |db|
    db.vm.hostname = "awx-demo-php2"
    db.vm.network :private_network, ip:"192.168.60.32"
  end
end
