---
# tasks file for myrole
- name: Install Apache.
  package:
    name: httpd
    state: present

- fail:

- name: Copy configuration file.
  copy:
    src: file.conf
    dest: /etc/httpd/conf.d/welcome.conf