---
- name: Install EPEL repo.
  yum:
    name: epel-release
    state: present

- name: Ensure firewalld is stopped.
  service:
    name: firewalld
    state: stopped

- name: Install Nodejs and npm.
  yum:
    name: npm
    state: present
    enablerepo: epel

- name: Install Forever (to run Nodejs app).
  npm:
    name: forever
    global: yes
    state: present
