---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Run uptime command and register uptime output.
      command: uptime
      register: uptime_output

    - name: Print out uptime command output.
      debug:
        var: uptime_output['stdout']
