---
- name: Update package manager if needed.
  package:
    update_cache: true
    #cache_valid_time: 3600
    
    #- debug: var=ansible_os_family

- name: Load variable files.       
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/apache_{{ ansible_os_family }}.yml"
    - "vars/apache_default.yml"