---
- hosts: all
  become: true

  vars_files:
    - vars.yml
  
  pre_tasks:
    - name: Update apt if needed.
      apt: 
        update_cache: true
        cache_valid_time: 3600

  handlers:
    - name: Restart solr
      service: 
        name: solr
        state: restarted
  
  #tasks:
  #  - name: Change config.
  #    command: Command to change some config.
  #    notify: Restart solr

  tasks:
    - name: Install Java.
      apt: 
        name: openjdk-8-jdk
        state: present
    
    - name: Download Solr.
      get_url:
        url: "https://downloads.apache.org/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz" # Idempotent purpose
        checksum: "{{ solr_checksum }}"

    - name: Expand Solr.
      unarchive: 
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/README" # Idempotent purpose, Ansible not know what inside tarball
      
    - name: Run Solr installation script.
      command: > # Every line below is only space between
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr 
        -p 8983 
      #creates: "{{ solr_dir }}/bin/solr"
      args:
        creates: "{{ solr_dir }}/bin/solr"

    - name: Ensure solr is started and at boot.
      service:
        name: solr
        state: started
        enabled: yes