Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.ssh.insert_key = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end

  # Server 1
  config.vm.define "server" do |app|
    app.vm.hostname = "server.mylocal"
    app.vm.network :private_network, ip:"192.168.60.100"
  end
end
