---
- name: Install Apache.
  hosts: all
  become: true

  vars:
    apache_package: apache2
    apache_service: apache2
  
  handlers:
    - name: restart apache2 service
      service:
        name: "{{ apache_service }}"
        state: restarted

  pre_tasks:
    - name: Override Apache vars for Red Hat.
      set_fact:
        apache_package: httpd
        apache_service: httpd
      when: ansible_os_family == 'RedHat'
    
    #- name: Update package manager.
    #  package:
    #    update_cache: true
    #    state: latest

  tasks:
    - name: Ensure Apache is installed.
      package:
        name: "{{ apache_package }}"
        state: present
    
    - name: Copy a web page.
      copy:
        content: |
          <html>
          <head><title>Hello World!</title></head>
          <body>Hello World!</body>
          </html>
        dest: "/var/www/html/index.html"
        owner: root
        group: root
        mode: 0644 
      notify: restart apache2 service
    
    - name: Ensure Apache is runnning and start at boot.
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true










